# Generated by Django 4.0 on 2023-09-28 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=254)),
                ('social_security_number', models.IntegerField()),
                ('mailing_address', models.CharField(max_length=254)),
                ('city_state_zipcode', models.CharField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('alternative_phone', models.IntegerField(default=0)),
                ('age_under_18', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('hours_available', models.JSONField()),
                ('job_time', models.CharField(max_length=254)),
                ('hours_weekly', models.IntegerField()),
                ('night_working', models.BooleanField()),
                ('begin_date', models.DateField()),
                ('have_been_employed_with_us', models.BooleanField()),
                ('us_citizen', models.BooleanField()),
                ('have_been_convicted', models.BooleanField()),
                ('has_drivers_license', models.BooleanField()),
                ('drivers_license_number', models.CharField(max_length=254)),
                ('drivers_license_state', models.CharField(max_length=254)),
                ('reviewed', models.BooleanField(default=False)),
                ('date_sent', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
